version: '3.9'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:80"